services:
  jenkins:
    image: jenkins/jenkins:2.471-jdk21
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/laoh/dev/jenkins:/var/jenkins_home
    links:
      - worker-1

  worker-1:
    image: jenkins/ssh-agent:latest-jdk21
    volumes:
      - /home/laoh/dev/jenkins_agent:/home/jenkins
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCrJ1zSa8jBu9I/h13WDn8pg3Pzp2cGEaCXN1StJY7Lp4KxpgIJa1ukKg/s+YVMW8AQOpicmSlJb6WXNkzgxnnV641u4tO485XK+kk28sGdVT61BOyUXZs/k/WAyR4Nl3OM9z69trwJrWQrFiUF8K2c8QWyj+w7o91gc9akjHKKZH9VhO49+W1g7v5na00KP+MEKa5gSvs7LA4sjsB0B+vDbCyCLe7Zv0jwx6lbahYdIAMSMZskT3020mnQ++u7cMpv+dBA9H4LPcI4ArR30k2EmkWI4GTW7B8nhfFmFExVpMm6jtDzDABhCpSv0MJZ1mC6gxGl7NLieQlC7Qew/t9CwJBRiHHiZ2O9J8iz2aXOXj75u5IXXC4nVaexf7uK5lfOikcBzhJ9bK/VFjyQCosdDVVA1B3Rtzkzv8Uw+3TnuONJMbtAUhPerC2xnzXUyeeWvDbhHVfbdw+bcde2wXJ87CpJ6pI8djjxkA/zvOA96e9NLVCzBfj5c8sYpnfbbU=